version: "3.3"

services:

  midpoint_data:
    image: tier/mariadb:mariadb10
    ports:
     - 3306:3306
    networks:
     - net
    volumes:
     - midpoint_mysql:/var/lib/mysql
     - midpoint_data:/var/lib/mysqlmounted
    environment:
     - CREATE_NEW_DATABASE=if_needed

  midpoint_server:
    image: tier/midpoint:latest
    ports:
      - 8443:443
    environment:
     - AUTHENTICATION
     - ENV
     - USERTOKEN
     - REPO_DATABASE_TYPE
     - REPO_JDBC_URL
     - REPO_HOST
     - REPO_PORT
     - REPO_DATABASE
     - REPO_USER
     - REPO_MISSING_SCHEMA_ACTION
     - REPO_UPGRADEABLE_SCHEMA_ACTION
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_MEM
     - TIER_BEACON_OPT_OUT
    networks:
     - net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
     - mp_sp-key.pem
     - mp_host-key.pem
    volumes:
     - midpoint_home:/opt/midpoint/var
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/shibboleth2.xml
       target: /etc/shibboleth/shibboleth2.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/idp-metadata.xml
       target: /etc/shibboleth/idp-metadata.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/sp-cert.pem
       target: /etc/shibboleth/sp-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/host-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/cachain.pem

  directory:
    build: ./directory/
    expose:
     - "389"
    ports:
     - "389:389"
    networks:
     - net
    volumes:
     - ldap:/var/lib/dirsrv

  idp:
    build: ./idp/
    depends_on:
     - directory
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    networks:
     - net
    ports:
     - "4443:4443"

networks:
  net:
    driver: bridge

secrets:
  mp_host-key.pem:
    file: ./configs-and-secrets/midpoint/httpd/host-key.pem
  mp_sp-key.pem:
    file: ./configs-and-secrets/midpoint/shibboleth/sp-key.pem
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/application/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/application/keystore_password.txt
    
volumes:
  midpoint_mysql:
  midpoint_data:
  midpoint_home:
  ldap:
