version: "3.3"

services:
  postgresql:
    build: ./postgresql/
    environment:
     - POSTGRES_PASSWORD=password
    expose:
     - 5432
    ports:
     - 5432:5432
    networks:
     - net
    volumes:
     - data:/var/lib/postgresql/data


networks:
  net:
    driver: bridge

volumes:
  data:
