#
# Building:
#  - docker-compose up --build
#
# It assumes that midpoint-3.9-SNAPSHOT-dist.tar.gz is present in the 'midpoint-server' directory. (TODO: eliminate this!)
#

version: "3.3"

services:
  midpoint-data:
    build: ./midpoint-data/
    expose:
     - 3306
    ports:
     - 3306:3306
    networks:
     - back
    volumes:
     - midpoint_data:/var/lib/mysql

  midpoint-server:
    build: ./midpoint-server/
    expose:
      - 443
    ports:
      - 8443:443
    environment:
     - AUTHENTICATION
     - ENV
     - USERTOKEN
     - REPO_DATABASE_TYPE
     - REPO_JDBC_URL
     - REPO_HOST
     - REPO_PORT
     - REPO_DATABASE
     - REPO_USER
     - REPO_PASSWORD_FILE
     - KEYSTORE_PASSWORD_FILE
     - MEM
    networks:
     - back
    secrets:
     - m_database_password.txt
     - m_keystore_password.txt
     - m_sp-key.pem
     - m_host-key.pem
    volumes:
     - midpoint_home:/opt/midpoint/var
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/shibboleth2.xml
       target: /etc/shibboleth/shibboleth2.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/idp-metadata.xml
       target: /etc/shibboleth/idp-metadata.xml
     - type: bind
       source: ./configs-and-secrets/midpoint/shibboleth/sp-cert.pem
       target: /etc/shibboleth/sp-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/host-cert.pem
     - type: bind
       source: ./configs-and-secrets/midpoint/httpd/host-cert.pem
       target: /etc/pki/tls/certs/cachain.pem

networks:
  back:    
    driver: bridge

secrets:
  m_host-key.pem:
    file: ./configs-and-secrets/midpoint/httpd/host-key.pem
  m_sp-key.pem:
    file: ./configs-and-secrets/midpoint/shibboleth/sp-key.pem
  m_database_password.txt:
    file: ./configs-and-secrets/midpoint/application/database_password.txt
  m_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/application/keystore_password.txt
    
volumes:
  midpoint_data:
  midpoint_home:
