#
#  Composition of midPoint and TIER MariaDB containers.
#
#  MariaDB serves as a repository for midPoint.
#
#  Features:
#   - a separate volume for repository data (MySQL database directory), so it persists between creation/removal cycle of this stack
#   - a separate volume for midPoint home directory, containing config.xml, logs, generated encryption keys, and so on
#   - MariaDB password is presented to midPoint as a Docker secret
#

version: "3.1"
services:

  mariadb:
    image: tier/mariadb:mariadb10
    deploy:
      restart_policy:
        condition: none
    volumes:
      - repo-db-data:/var/lib/mysqlmounted
    networks:
      - webnet
    secrets:
      - repo-password

  mariadbadminer:
    image: adminer
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - mariadb
    ports:
      - 18080:8080
    networks:
      - webnet

  midpoint:
    image: midpoint
    deploy:
      restart_policy:
        condition: none
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    volumes:
      - midpoint-home:/opt/midpoint/var           # change this if MP_DIR changes
    networks:
      - webnet
    secrets:
      - repo-password

networks:
  webnet:

volumes:
  repo-db-data:
  midpoint-home:

secrets:
  repo-password:
    file: repo-password.txt
