#
# This is a file with additions to ../midpoint/docker-compose.yml file, to be used in the following way:
#
# (in ../midpoint directory)
#
# $ docker-compose -f docker-compose.yml -f ../demo/postgresql/midpoint-additions.yml up --build
#
# It expects that PostgreSQL is started as part of midPoint composition. So there will be three containers there:
#
# 1) midpoint-server
# 2) postgresql
# 3) midpoint-data    <-- this is the original MariaDB container; it will execute command of 'true' i.e. exiting just upon the startup
#

version: "3.3"

services:
  postgresql:
    build: ../demo/postgresql/postgresql/
    entrypoint: ["/docker-entrypoint.sh", "postgres"]           # for some reasons this is needed for the correct initialization
    environment:
     - POSTGRES_PASSWORD=password
    expose:
     - 5432
    ports:
     - 5432:5432
    networks:
     - back
    volumes:
     - postgresql_data:/var/lib/postgresql/data

  midpoint-server:
    environment:
     - REPO_DATABASE_TYPE=postgresql
     - REPO_HOST=postgresql
     - REPO_PORT=5432
     - REPO_DATABASE=midpoint
     - REPO_USER=midpoint

  # effectively disable original MariaDB service
  midpoint-data:
    image: alpine:latest
    command: "true"
    entrypoint: "true"

volumes:
  postgresql_data:
